name: supergreat
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.1
  google_fonts: ^2.0.0
  solid_bottom_sheet: ^0.1.9
  flutter_feather_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  contained_tab_bar_view: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/